### ISSUE TITLE
Restore the ability for plugins to filter video lists

### ISSUE THREAD

**Issue by stevegrunwell** [101videos/wp101plugin#50]
[Version 5.0.0 deprecated a lot of the old WP101 actions and filters](https://github.com/leftlane/wp101plugin/blob/master/includes/deprecated.php), but there are instances where large multisite installations depended on these to trim out videos.

Any hooks around controlling series + topics should be restored and able to handle both legacy IDs and slugs.

**Comment by stevegrunwell** [comment]
@leftlane I'm curious how backwards-compatible you're looking to be here. The data structures that come from the new SaaS are rather different, and while we can add in the old (or newer, replacement) filters, sites may still find themselves needing to update the filters accordingly.

There are three ways I can reasonably see this going (in increasing level of complexity):

1. Restore and/or add new filters, enabling people to write code like the following:
    ```php
    add_filter( 'wp101_get_playlist', function ( $playlist ) {
        $slugs = ['create-pages', 'custom-menus'];

        foreach ( $playlist as $series_key => $series ) {
            foreach ( $series['topics'] as $key => $topic ) {
                if ( in_array( $topic['slug'], $slugs, true ) ) {
                    unset( $playlist[ $series_key ]['topics'][ $key ] );
                }
            }
        }

        return $playlist;
    } );
    ```
2. Add helper method(s) to exclude series/topics by slug:
    ```php
    add_filter( 'wp101_excluded_topics', function ( $topics ) {
        $topics[] = 'create-pages';
        $topics[] = 'custom-menus';

        return $topics;
    } );
    ```
3. Map legacy filters to existing data (e.g. if someone was excluding ID `4` before, filter out a topic with legacy ID of `4`.
    * In order to cover this properly, we'd pretty much have to map the new schema to the old to pass to the filter, then apply the changes. It's do-able, but definitely more involved.

Of the three, I'd lean towards option 2: it gives users a clear way to say "these are the topics/series I wish to exclude, referenced by slug" but does require an update to their code.

**Comment by leftlane** [comment]
I'm with you. I like option 2. Let's rock with that direction.

**Comment by stevegrunwell** [comment]
@leftlane Thanks for clarifying. I've tossed this over to @jcosper if he has bandwidth.
