### ISSUE TITLE
Report of videos not loading for a client, plus cookie error?

### ISSUE THREAD

**Issue by leftlane** [101videos/wp101plugin#69]
Customer #298: Gretchen Acheson reports, “I've never encountered this before, but my client cannot load any of the videos.”

Screenshot: ![image](https://user-images.githubusercontent.com/1584080/74554932-4269d000-4f20-11ea-80b6-d9547eac773a.png)

In case this is helpful, these are the errors I'm seeing:
![image-1](https://user-images.githubusercontent.com/1584080/74554983-56153680-4f20-11ea-851d-3d5d03e83ee7.png)

It appears to me that the cookie notice is just an alert, not an error. I don't see any outright errors related to the WP101 Plugin... though we'll want to address the SameSite cross-site cookie issue to ensure it doesn't cause problems with future releases of Chrome.

Is the video failing to load related, or likely caused by something else?

**Comment by stevegrunwell** [comment]
The cookies coming back from the app shouldn't even really be required, considering we're passing public API keys to the application to get the Vimeo URLs.

I would agree with your assessment that Sumo may be interfering; JavaScript errors in unrelated scripts can cause the JS to stop executing on the page. I'm also curious what the sandbox being referenced is from, as this seems similar to https://wordpress.org/support/topic/add-media-button-not-working-57/

**Comment by leftlane** [comment]
Hmm... I'm logged into the client's admin area. I've temporarily deactivated/reactivated all the plugins I suspected, but still getting this error anytime I click a link to a video: 
<img width="1442" alt="Screen Shot 2020-02-14 at 1 22 54 PM" src="https://user-images.githubusercontent.com/1584080/74560949-3df7e400-4f2d-11ea-9386-97683cd49f04.png">

I'm actually not seeing errors for any other plugin. Just the 403 for the Vimeo URL: https://fresnel.vimeocdn.com/*

Looked up the site's host to see if it's in a country that may have blocked access to Vimeo. Nope. Great Britain. 

Any other suggestions I might try?

**Comment by leftlane** [comment]
`ping: cannot resolve https://fresnel.vimeocdn.com/: Unknown host`

Starting to suspect that Vimeo's CDN is just experiencing an outage on that particular node. Not our problem?

**Comment by leftlane** [comment]
For future reference, this was due to an overly aggressive use of `display: none` on iframes by the RankMath plugin. Resolved with a temporary filter to hide the `version-control` module in RankMath. Thanks so much for the fix, @stevegrunwell!
